as yet unclassified
testAcceptance2
	"
	self debug: #testAcceptance2
	"

 	self assert: ((self acceptance: 2) beginsWith: 'ERROR LOGGINGTEST test: 1 
TEMP LOGGINGTEST LoggingTest-acceptance: 2 
DEBUG LOGGINGTEST LoggingTest-acceptance: 2 
TEMP LOGGINGTEST test: 3 
TEMP MYOWN test: 4 
ERROR MYOWN test: 5 
TEMP LOGGINGTEST LoggingTest>>#testAcceptance2 {as yet unclassified}
category: ''Instance'' 
TEMP LOGGINGTEST NAMED SLOTS
testSelector: testAcceptance2
log: a LogCurrent

TEMP LOGGINGTEST category: ''Class'' 
TEMP LOGGINGTEST LoggingTest
CLASS NAMED SLOTS
superclass: TestCase
methodDict: a MethodDictionary(')