convert
primCalcVertexNormals: argVertexNormals vertexCount: argVertexCount faces: argFaces faceNormals: argFaceNormals shadeAngleCos: shadeAngleCosValue


	<primitive: 'primitiveCalcVertexNormals' module: 'TLoad3DSMaxPlugin'>
	^ nil
	"TLoad3DSMaxPlugin doPrimitive: 'primCalcVertexNormals:vertexCount:faces:faceNormals:shadeAngleCos:' withArguments: {argVertexNormals. argVertexCount. argFaces. argFaceNormals. shadeAngleCosValue}."